z_dim: ${vi_model.z_dim}
epsilon_dim: ${vi_model.epsilon_dim}
hidden_dim: 256
num_layers: 16
logit: ${vi_model.uniform}
device: ${device}
use_optimizer: true
weight_decay: 0.0
warmup:
  enabled: true
  lr: 2.0e-4
  weight_decay: 0.0
  batch_size: 128
  epochs: 2000
