seed: 7
cuda_visible_devices: "0"
use_cuda: true

runner_type: KDVI
target_type: 8_gaussians_small
vi_model_type: ConditionalGaussian
vi_model_config_path: configs/vi_models/ConditionalGaussian-Eps32-ELU-LogStd.yaml

train:
  epochs: 100000
  batch_size: 128
  vi:
    lr: 2.0e-3
    scheduler:
      type: StepLR
      step_size: 5000
      gamma: 0.75
  annealing:
    enabled: true
    scheme: linear
    steps: 50000
  kdvi:
    mcmc_type: sgld
    mcmc_steps: 5
    mcmc_step_size: 0.05
    kernel: laplace_l2
    fit_bandwidth_on: x
    step_size_schedule:
      type: coupled
  grad_clip: null
  log:
    metric_log_freq: 5000
    loss_log_freq: 1000
    reverse_log_freq: 5000
    time_avg_window: 500
  checkpoint:
    enabled: false
    freq: 200000
  sample:
    freq: 200000
    num: 5000
  plot:
    freq: 10000
    num: 2000
  ema:
    enabled: false
    beta: 0.999

metric:
  kl_ite:
    enabled: true
    num_samples: 5000
  w2:
    enabled: true
    num_samples: 5000
    num_projections: 100
  elbo:
    enabled: false
    batch_size: 128
    num_batches: 1
    num_z_samples: 100
  fisher:
    enabled: false
    num_samples: 1000
    num_is_samples: 512
  ksd:
    enabled: false
    num_samples: 1000
  mmd:
    enabled: false
    num_samples: 1000
  bnn:
    enabled: false
    num_samples: 500
  expected_log_marginal:
    enabled: false
