seed: 42
cuda_visible_devices: "0"
use_cuda: true

runner_type: KSIVI
target_type: Bnn_yacht
vi_model_type: ConditionalGaussian
vi_model_config_path: configs/vi_models/ConditionalGaussian-Bnn-ksivi.yaml

target:
  data:
    batch_size: 100
    batch_mode: cyclic
    dev_fraction: 0.1
    dev_max_size: 500

train:
  epochs: 100000
  batch_size: 100
  grad_clip: 1.0
  pretrain:
    enabled: true
    steps: 100
    lr: 1.0e-2
    batch_size: 100
  ema:
    enabled: true
    beta: 0.999
  vi:
    lr: 1.0e-3
    var_lr: 1.0e-3
    betas: [0.9, 0.999]
    scheduler:
      type: StepLR
      step_size: 3000
      gamma: 0.9
  annealing:
    enabled: false
    scheme: linear
    steps: 5000
  ksivi:
    statistic: v
    kernel: gaussian
    detach_kernel: false
    log_p_reg: 1.0
    log_p_reg_mode: always
  log:
    metric_log_freq: 1000
    loss_log_freq: 100
    reverse_log_freq: 500
  checkpoint:
    enabled: true
    freq: 5000
  sample:
    freq: 1000
    num: 100
  plot:
    freq: 999999
    num: 100

metric:
  kl_ite:
    enabled: false
    num_samples: 10000
  w2:
    enabled: false
    num_samples: 10000
    num_projections: 1000
  elbo:
    enabled: false
    batch_size: 128
    num_batches: 5
    num_z_samples: 200
  ksd:
    enabled: true
    num_samples: 100
  mmd:
    enabled: false
  bnn:
    enabled: true
    num_samples: 100
  fisher:
    enabled: false
  expected_log_marginal:
    enabled: false
