z_dim: ${target.z_dim}
device: ${device}
epsilon_dim: 100
hidden_dim: 128
num_layers: 2
activation: relu
variance_parameterization: logvar
global_log_var_init: -2.0
global_log_var_min: -12
uniform: false